language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest


git:
  depth: 3

install: python -m pip install -e .[tests]

script: coverage run BlackRobustFlow.py data/pepsi

after_success: coveralls
