language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest


git:
  depth: 3

install: 
  - cd bin
  - cmake ../src
  - make
  
  - cd ..
  - pip install -e .[tests]

script: 
   - cd bin
   - make test
   - cd ..
   
   - pytest -v

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run ../tests/test_all.py;
    coveralls;
    fi
    
after_failure: 
  - cd $TRAVIS_BUILD_DIR/bin
  - ctest -V
