language: python

python:
  - 3.6

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false

git:
  depth: 3

install: 
    - cd bin
    - cmake ../src
    - make
    - cd ..

script:
    - python BlackRobustFlow.py data/pepsi
