language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

install: python -m pip install -e .[tests]

script: coverage run BlackRobustFlow.py data/pepsi

after_success: coveralls
